apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: chat-app
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: admin
  MONGO_INITDB_ROOT_PASSWORD: admin123
  MONGO_INITDB_DATABASE: chatdb
